Session13 (2)/project/blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('new/', views.new, name='new'),
    path('detail/<int:post_id>', views.detail, name='detail'),
    path('update/<int:post_id>', views.update, name='update'),
    path('delete/<int:post_id>', views.delete, name='delete'),
    path('delete_comment/<int:post_id>/<int:comment_id>', views.delete_comment, name='delete_comment'),
    path('recomment/<int:post_id>/<int:comment_id>', views.recomment, name='recomment'),
    path('delete_recomment/<int:post_id>/<int:comment_id>/<int:recomment_id>/', views.delete_recomment, name='delete_recomment'),
    path("registration/signup/", views.signup, name="signup"),
    path("registration/login/", views.login, name="login"),
    path("registration/logout/", views.logout, name="logout"), 
]

Session13 (2)/project/management/urls.py
from django.urls import path
from management import views

app_name = 'management'
urlpatterns = [
    # management
    path('', views.home, name = 'home'),
]

Session13 (2)/project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts', include('allauth.urls')),
    path('management/', include('management.urls')),
    path('blog/', include('blog.urls')),
]


Session13 (2)/project/blog/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, timedelta, date
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=200, verbose_name="TITLE")
    content = models.TextField()
    deadline = models.DateField()
    create_dt = models.DateTimeField(auto_now_add=True)
    update_dt = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        ordering = ('-create_dt', 'author')

    def __str__(self):
        return f'{self.title} - {self.author}'
    
    def get_absolute_url(self):
        return reverse(f'blog:post_detail', args=[self.id])
    
    def get_previous(self):
        return self.get_previous_by_create_dt()
    
    def get_next(self):
        return self.get_next_by_create_dt()

    def publish(self):
        self.created_date = timezone.now()
        self.save()
    
    def end_date(self):
        deadline = self.deadline
        today = date.today()
        d_day = (deadline - today).days
        return d_day
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    create_dt = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-create_dt', 'post', 'author')

    def __str__(self):
        return f'{self.title} - {self.author}'
    
class Recomment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='recomments')
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='recomments')
    content = models.TextField(default='')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='recomments')


    def __str__(self):
        return self.title
    

    

Session13 (2)/project/management/models.py
from django.db import models
from django.contrib.auth.models import User
#	Create	your	models	here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    age	= models.PositiveIntegerField(help_text="User Age", blank=True,	null=True)

Session13 (2)/project/blog/views.py
from django.shortcuts import render, redirect
from .models import Post, Comment, Recomment
from django.utils import timezone
from datetime import timedelta
from django.contrib.auth.models import User
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def login(request):
   if request.method == 'POST':
       username = request.POST['username']
       password = request.POST['password']

       user = auth.authenticate(username=username, password=password)

       if user is not None:
            auth.login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect(request.GET.get('next', '/blog/'))
       error = "아이디 또는 비밀번호가 틀립니다"
       return render(request, 'registration/login.html', {"error":error})

   return render(request, 'registration/login.html')


def logout(request):
   auth.logout(request)
   return redirect('blog:home')

def signup(request):
   if request.method == 'POST':
       username = request.POST['username']
       password = request.POST['password']
       
       exist_user = User.objects.filter(username=username)

       if exist_user:
           error = "이미 존재하는 아이디입니다"
           return render(request, 'registration/signup.html', {"error": error})
       
       new_user = User.objects.create_user(username=username, password=password)
       auth.login(request, new_user, backend='django.contrib.auth.backends.ModelBackend')
       return redirect('blog:home')

   return render(request, 'registration/signup.html')

def home(request):
    posts = Post.objects.all().order_by("deadline")

    return render(request, 'blog/home.html', {'posts': posts})

@login_required(login_url="/registration/login/")
def new(request):
    if request.method == 'POST':
        new_post = Post.objects.create(
            title = request.POST['title'],
            content = request.POST['content'],
            deadline = request.POST['deadline'],
            author=request.user
    )
        return redirect('blog:detail', new_post.id)

    return render(request, 'blog/new.html')

@login_required(login_url="/registrations/login/")
def detail(request, post_id):
   post = Post.objects.get(id=post_id)
   print(post)
   if request.method == 'POST':
       content = request.POST['content']
       Comment.objects.create(
           post = post,
           content = content,
           author = request.user
       )
       return redirect('blog:detail', post_id)

   return render(request, 'blog/detail.html', {'post': post})


def update(request, post_id):
    post = Post.objects.get(id = post_id)

    if request.method == 'POST':
        Post.objects.filter(id = post_id).update(
            title = request.POST['title'],
            content = request.POST['content'],
            deadline = request.POST['deadline']
        )
        return redirect('blog:detail', post_id)
    
    return render(request, 'blog/update.html', {'post': post})

def delete(request, post_id):
    post = Post.objects.get(id = post_id)
    post.delete()

    return redirect('blog:home')

def delete_comment(request, post_id, comment_id):
    comment = Comment.objects.get(id = comment_id)
    comment.delete()
    return redirect('blog:detail', post_id)


def recomment(request, post_id, comment_id):
    comment = Comment.objects.get(id = comment_id)
    if request.method == "POST":
        recomments = Recomment.objects.create(
            comment = comment,
            content = request.POST['content'],
        )
        return redirect('blog:detail', post_id)

def delete_recomment(request, post_id, recomment_id):
    recomment = Recomment.objects.get(id = recomment_id)
    recomment.delete()
    return redirect('blog:detail', post_id)

Session13 (2)/project/management/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'management/home.html')

Session13 (2)/project/blog/templates/blog/base.html
<head>
    {% load account socialaccount %}
    {% providers_media_js %}
    {% load static %}
    <meta charset="UTF-8" />
    <link rel="shortcut icon" href="{% static 'favicon.png' %}" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Ceviche+One&family=Inter:wght@900&family=Jua&family=Koulen&display=swap"
      rel="stylesheet"
   />
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}" />
    {% block css %} {% endblock css %}
    <title>Project</title>
  </head>
 
 
  <body>
    <div id="nav_bar" >
      <div class="navbar__logo">
        <a href="{% url 'blog:home'%}">🏠HOME</a>
      </div>
      <ul class="navbar__menu">
        {% if user.is_authenticated %}
        <span class="navbar__menu__item">HELLO, {{user.username}} / </span>
          <li class="navbar__menu__item">
            <a href="{% url 'blog:logout'%}">로그아웃 / </a>
          </li>
          <li class="navbar__menu__item">
            <a href="{% url 'blog:new' %}">NEW / </a>
          </li>
          {% else %}
          <li class="navbar__menu__item">
            <a href="{% url 'blog:signup' %}">회원가입 / </a>
          </li>
          <li class="navbar__menu__item">
            <a href="{% url 'blog:login' %}">로그인 / </a>
          </li>
        </ul>
          
          <form
            method = "POST" 
            action="{% provider_login_url 'kakao' %}">
              {% csrf_token %} {{ form.as_p }} {% if redirect_field_value %}
              <input
              type ="hidden"
              name="{{ redirect_field_name }}"
              value="{{ redirect_field_value }}"/>
              {% endif %}
              <button class = "primaryAction" type="submit"> 
                <img id="kakao" src="../static/img/kakao.png">
              </button>
            </form>
            <span>   /   </span>
            <form
            method = "POST" 
            action="{% provider_login_url 'google' %}">
              {% csrf_token %} {{ form.as_p }} {% if redirect_field_value %}
              <input
              type ="hidden"
              name="{{ redirect_field_name }}"
              value="{{ redirect_field_value }}"/>
              {% endif %}
              <button class = "primaryAction" type="submit">
                <img id="google" src="../static/img/google.png">
              </button>
          </form>


          {% endif %}

          
    </div>
    <div class="title">{% block title %} {% endblock title %}</div>
    <div class="container">{% block content %} {% endblock content %}</div>
    <!-- footer -->
  <div class="footer">{% block footer %} {% endblock footer %} </div>
  
</body>
 </html>
 

Session13 (2)/project/blog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block css %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'detail.css' %}" />
{% endblock %} 

{% block title %} DETAIL {% endblock %} 

{% block content %}
  <body>
    <div class="all">
        <div id="title">
          <h2>📍TITLE</h2>
          <p class="detail">{{post.title}}</p>
        </div>

        <div id="content">
          <h2>✨CONTENT</h2>
          <p class="detail">{{post.content}}</p>
        </div>
      <br />

        <div id="dead">
          <h2>🗓️UNTIL</h2>
          <p class="detail">{{post.deadline}}</p>
        </div>

      <!-- comments 섹션 -->
      <div class="comments">
        <form method="POST">
          {% csrf_token %}
          <input type="text" name="content" placeholder="댓글 입력">
          <button type="submit">작성하기</button>
        </form>

        <div id="comment">
          {% for comment in post.comments.all %}
          <li>{{comment.content}}</li>
          {% if user.pk == comment.author.pk and user.is_authenticated %}
          <a href="{% url 'delete_comment' post.id comment.id %}">댓글 삭제</a>
          {% endif %}
        </div>
        

        <div class="recomment" style="margin-left: 100px;">
          {% for recomment in comment.recomments.all %}
          <li style="list-style-type: none;"> - {{recomment.content}}</li>
          {% endfor %}
        </div>

        <form action="{% url 'recomment' post.id comment.id %}" method="POST">
          {% csrf_token %}
          <input type="text" name="content" placeholder="대댓글 입력">
          <button type="submit">작성하기</button>
        </form>
        {% endfor %}
      </div> 
      <br />
    <br />
    <div>
      <a href="{% url 'blog:home'%}">🏠HOME</a> <br /><br />
      {% if user.is_authenticated and user.pk == post.author.pk %}
      <a href="{% url 'blog:update' post.id %}">🔧EDIT</a><br /><br />
      <a href="{% url 'blog:delete' post.id %}">💣DELETE</a>
      {% endif %}
    </div>
    {% endblock %}
    <br>
    <br>
    <br>
    {% block footer %} copyright 2023. 원경 all rights reserved {% endblock %}
  </body>
</html>

Session13 (2)/project/blog/templates/blog/home.html
{% extends 'blog/base.html' %}

{% block css %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'home.css' %}" />
{% endblock %} 

{% block title %} TO-DO {% endblock %} 

{% block content %}
  <body>
    <div class="container">
      <div class="letters">
        <ul class="nodot">
          {% for post in posts %}
          <li style="list-style: none">
            <input
              type="checkbox"
              name="{{post.title}}"
              value="{{post.title}}"
            />
            <a href="{% url 'blog:detail' post.id %}">
              {{ post.title }} [D-{{ post.end_date }}]
            </a>
          </li>
          {% endfor %}
        </ul>
      </div>
    
      <br />
      <br />
      <div class="link">
        <a href="{% url 'blog:new' %}">✍️ NEW!</a>
      </div>

    </div>
    {% endblock %}
    <br>
    <br>
    <br>
    {% block footer %} copyright 2023. 원경 all rights reserved {% endblock %}
  </body>
</html>

Session13 (2)/project/blog/templates/blog/new.html
{% extends 'blog/base.html' %}

{% block css %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'new.css' %}" />
{% endblock %} 

{% block title %} NEW! {% endblock %} 

{% block content %}
  <body>
    <form action="" method="post">
      {% csrf_token %}
      <div class="body">
        <label for="title">📍TITLE</label>
        <input
          type="text"
          name="title"
          id="title"
          placeholder="제목을 입력하세요"
        />

        <br />

        <div>
          <label for="content">✨CONTENT</label>
          <br />
          <textarea
            name="content"
            id="content"
            cols="30"
            rows="10"
            placeholder="내용을 입력하세요"
          ></textarea>
        </div>
        <br />

        <div>
          <label for="deadline">🗓️UNTIL</label>
          <br />
          <input
            type="date"
            id="deadline"
            name="deadline"
            placeholder="0000-00-00"
          />
        </div>
        <br />
        <button type="submit">SUBMIT</button>
        <br /><br />
      </div>
      <a href="{% url 'blog:home'%}">🏠HOME</a>
    </form>
    {% endblock %}
    <br>
    <br>
    <br>
    {% block footer %} copyright 2023. 원경 all rights reserved {% endblock %}
  </body>
</html>

Session13 (2)/project/blog/templates/blog/update.html
{% extends 'blog/base.html' %}

{% block css %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'update.css' %}" />
{% endblock %} 

{% block title %} EDIT {% endblock %} 

{% block content %}
  <body>
    <form action="" method="post">
      {% csrf_token %}
      <div class="body">
        <label for="title">📍TITLE</label>
        <input type="text" name="title" id="title" value="{{post.title}}" />
        <br />

        <div>
          <label for="content">✨CONTENT</label>
          <br />
          <textarea name="content" id="content" cols="30" rows="10">
{{ post.content }}</textarea
          >
        </div>
        <br />

        <div>
          <label for="deadline">🗓️UNTIL</label>
          <br />
          <input
            type="date"
            id="deadline"
            name="deadline"
            placeholder="0000-00-00"
          />
        </div>

        <br />
        <button type="submit">EDIT</button>
      </div>
    </form>
    {% endblock %}
    <br>
    <br>
    <br>
    {% block footer %} copyright 2023. 원경 all rights reserved {% endblock %}
  </body>
</html>

Session13 (2)/project/management/templates/management/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
        <h1>독후감 블로그-회원관리</h1>
        <a href="{% url 'blog:home' %}">독후감 블로그</a>
    </div>    
</body>
</html>